name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.9.0  # Choose your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Run tests
      run: npm test
